istio:
  enabled: true

podAnnotations:
  sidecar.istio.io/inject: "true"
  traffic.sidecar.istio.io/includeInboundPorts: "*"
  traffic.sidecar.istio.io/excludeInboundPorts: "9443"

operator:
  env:
  - name: MINIO_OPERATOR_TLS_ENABLE
    value: "on"
  - name: CLUSTER_DOMAIN
    value: "cluster.local"
  - name: WATCHED_NAMESPACE
    value: ""
  - name: PROMETHEUS_NAMESPACE
    value: "monitoring"
