[package]
[package.create]
max_package_size = 1000000000

[package.create.set]
repo = "https://repo1.dso.mil/big-bang/product/packages/minio-operator.git"
tag = "4.5.4-bb.0"
name = "minio-operator"
values_file = "../minio-operator/values.yaml"
path = "./chart"

