[package]
[package.create]
max_package_size = 1000000000

[package.create.set]
repo = "https://repo1.dso.mil/big-bang/product/packages/minio.git"
tag = "4.5.4-bb.3"
name = "minio"
values_file = "../minio/values.yaml"
path = "./chart"
