on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: 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
          script: |
               const res = await github.rest.packages.listPackagesForOrganization({
                                   package_type: 'container',
                                   org: 'defenseunicorns'
                                 });
               console.log(res)


                  
            
