on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PACKAGES_SECRET }}
          script: |
               const script = require('./package-finder.js')
               await script({github})
               cat README.md



                  
            
